# Generated by Django 3.2.5 on 2021-07-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_shopuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='first_name',
            field=models.TextField(blank=True, max_length=128, verbose_name='о себе'),
        ),
    ]
