# Generated by Django 3.2.5 on 2021-07-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_shopuserprofile_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuserprofile',
            name='first_name',
        ),
        migrations.AddField(
            model_name='shopuserprofile',
            name='home_town',
            field=models.CharField(blank=True, max_length=128, verbose_name='home_town'),
        ),
    ]
